# .golangci.yml
version: "2"

linters:
  default: none
  enable:
    - logchecker
  settings:
    custom:
      logchecker:
        type: "module"
        description: "Checks that log messages"
        settings: